#for mongo

version: '3'
services:
  mongodb-primary:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_REPLICA_SET_NAME=rs0
    volumes:
      - mongo-data-primary:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongodb-secondary:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data-secondary:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongodb-arbiter:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb-primary

volumes:
  mongo-data-primary:
    driver: local
  mongo-data-secondary:
    driver: local
